name: CI

on:
  push:
    branches: ['**']

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Commit & Push updated syntaxes
        if: github.event_name == 'push'
        run: |
          set -e
          echo "Checking for changes in syntaxes/"
          if git diff --quiet --exit-code -- syntaxes/; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add syntaxes/
          if git diff --cached --quiet --exit-code; then
            echo "No staged changes after add."
            exit 0
          fi
            
          commit_msg="chore(ci): update generated syntaxes [skip ci]"
          git commit -m "$commit_msg"
          # Rebase in case of concurrent updates
          git pull --rebase origin "${GITHUB_REF#refs/heads/}" || true
          git push origin HEAD:"${GITHUB_REF#refs/heads/}"
        shell: bash

